const { COMMIT_CONFIG } = require('./commit');

COMMANDS = {
  COMMIT: 'commit',
  BRANCH: 'branch',
  CONFIG: 'config',
  HELP: 'help',
};

COMMANDS_SHORT = {
  C: 'c',
  B: 'b',
  CFG: 'cfg',
  H: 'h',
}

const COMMAND_NAMES = {
  [COMMANDS.COMMIT]: COMMANDS.COMMIT,
  [COMMANDS_SHORT.C]: COMMANDS.COMMIT,
  [COMMANDS.BRANCH]: COMMANDS.BRANCH,
  [COMMANDS_SHORT.B]: COMMANDS.BRANCH,
  [COMMANDS.CONFIG]: COMMANDS.CONFIG,
  [COMMANDS_SHORT.CFG]: COMMANDS.CONFIG,
  [COMMANDS.HELP]: COMMANDS.HELP,
  [COMMANDS_SHORT.H]: COMMANDS.HELP,
};

const COMMANDS_CONFIG = {
  [COMMAND_NAMES[COMMANDS.COMMIT]]: COMMIT_CONFIG,
  [COMMAND_NAMES[COMMANDS.BRANCH]]: {},
  [COMMAND_NAMES[COMMANDS.CONFIG]]: {},
  [COMMAND_NAMES[COMMANDS.HELP]]: {},
};

module.exports = {
  COMMANDS,
  COMMANDS_SHORT,
  COMMAND_NAMES,
  COMMANDS_CONFIG,
};
